---
distFolder: dist
setup:
- name: Setup Node.js v12.22.x
  action: actions/setup-node@v1
  properties:
    node-version: v12.22.x
prepare:
  name: Prepare project build environment
  command: npm ci
build:
  name: Build Nuxt
  command: npm run generate
